// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthChallenge = `-- name: ConsumeAuthChallenge :exec
UPDATE auth_challenges
SET consumed_at = NOW()
WHERE id = $1::uuid
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeAuthChallenge(ctx context.Context, challengeID string) error {
	_, err := q.db.Exec(ctx, consumeAuthChallenge, challengeID)
	return err
}

const consumeOAuthAuthorizationCode = `-- name: ConsumeOAuthAuthorizationCode :exec
UPDATE oauth_authorization_codes
SET consumed_at = NOW()
WHERE id = $1::uuid
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeOAuthAuthorizationCode(ctx context.Context, codeID string) error {
	_, err := q.db.Exec(ctx, consumeOAuthAuthorizationCode, codeID)
	return err
}

const createAuthChallenge = `-- name: CreateAuthChallenge :one
INSERT INTO auth_challenges (challenge_type, user_id, data, expires_at)
VALUES ($1, $2::uuid, $3, $4)
RETURNING id::text AS id,
          challenge_type,
          user_id::text AS user_id,
          data,
          expires_at,
          consumed_at,
          created_at
`

type CreateAuthChallengeParams struct {
	ChallengeType string             `json:"challenge_type"`
	UserID        pgtype.UUID        `json:"user_id"`
	Data          []byte             `json:"data"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type CreateAuthChallengeRow struct {
	ID            string             `json:"id"`
	ChallengeType string             `json:"challenge_type"`
	UserID        string             `json:"user_id"`
	Data          []byte             `json:"data"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) (CreateAuthChallengeRow, error) {
	row := q.db.QueryRow(ctx, createAuthChallenge,
		arg.ChallengeType,
		arg.UserID,
		arg.Data,
		arg.ExpiresAt,
	)
	var i CreateAuthChallengeRow
	err := row.Scan(
		&i.ID,
		&i.ChallengeType,
		&i.UserID,
		&i.Data,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createExternalIdentity = `-- name: CreateExternalIdentity :one
INSERT INTO external_identities (user_id, provider, provider_subject, email, metadata)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5
)
RETURNING id::text AS id,
          user_id::text AS user_id,
          provider,
          provider_subject,
          email,
          metadata,
          created_at
`

type CreateExternalIdentityParams struct {
	UserID          string      `json:"user_id"`
	Provider        string      `json:"provider"`
	ProviderSubject string      `json:"provider_subject"`
	Email           pgtype.Text `json:"email"`
	Metadata        []byte      `json:"metadata"`
}

type CreateExternalIdentityRow struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	Email           pgtype.Text        `json:"email"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) (CreateExternalIdentityRow, error) {
	row := q.db.QueryRow(ctx, createExternalIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.Metadata,
	)
	var i CreateExternalIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAccessToken = `-- name: CreateOAuthAccessToken :one
INSERT INTO oauth_access_tokens (token_hash, token_jti, client_id, user_id, scope, expires_at)
VALUES (
  $1,
  $2,
  $3,
  $4::uuid,
  $5,
  $6
)
RETURNING id::text AS id,
          token_hash,
          token_jti,
          client_id,
          user_id::text AS user_id,
          scope,
          expires_at,
          revoked_at,
          created_at
`

type CreateOAuthAccessTokenParams struct {
	TokenHash string             `json:"token_hash"`
	TokenJti  string             `json:"token_jti"`
	ClientID  string             `json:"client_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Scope     string             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateOAuthAccessTokenRow struct {
	ID        string             `json:"id"`
	TokenHash string             `json:"token_hash"`
	TokenJti  string             `json:"token_jti"`
	ClientID  string             `json:"client_id"`
	UserID    string             `json:"user_id"`
	Scope     string             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOAuthAccessToken(ctx context.Context, arg CreateOAuthAccessTokenParams) (CreateOAuthAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, createOAuthAccessToken,
		arg.TokenHash,
		arg.TokenJti,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i CreateOAuthAccessTokenRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenJti,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAuthorizationCode = `-- name: CreateOAuthAuthorizationCode :one
INSERT INTO oauth_authorization_codes (
  code_hash,
  client_id,
  user_id,
  redirect_uri,
  scope,
  code_challenge,
  code_challenge_method,
  expires_at
)
VALUES (
  $1,
  $2,
  $3::uuid,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id::text AS id,
          code_hash,
          client_id,
          user_id::text AS user_id,
          redirect_uri,
          scope,
          code_challenge,
          code_challenge_method,
          expires_at,
          consumed_at,
          created_at
`

type CreateOAuthAuthorizationCodeParams struct {
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	UserID              string             `json:"user_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scope               string             `json:"scope"`
	CodeChallenge       pgtype.Text        `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text        `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

type CreateOAuthAuthorizationCodeRow struct {
	ID                  string             `json:"id"`
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	UserID              string             `json:"user_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scope               string             `json:"scope"`
	CodeChallenge       pgtype.Text        `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text        `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOAuthAuthorizationCode(ctx context.Context, arg CreateOAuthAuthorizationCodeParams) (CreateOAuthAuthorizationCodeRow, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.Scope,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i CreateOAuthAuthorizationCodeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (id, name, redirect_uris, scopes, confidential, client_secret_hash, require_pkce)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id,
          name,
          redirect_uris,
          scopes,
          confidential,
          created_at,
          client_secret_hash,
          require_pkce
`

type CreateOAuthClientParams struct {
	ID               string      `json:"id"`
	Name             string      `json:"name"`
	RedirectUris     []string    `json:"redirect_uris"`
	Scopes           []string    `json:"scopes"`
	Confidential     bool        `json:"confidential"`
	ClientSecretHash pgtype.Text `json:"client_secret_hash"`
	RequirePkce      bool        `json:"require_pkce"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ID,
		arg.Name,
		arg.RedirectUris,
		arg.Scopes,
		arg.Confidential,
		arg.ClientSecretHash,
		arg.RequirePkce,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.Scopes,
		&i.Confidential,
		&i.CreatedAt,
		&i.ClientSecretHash,
		&i.RequirePkce,
	)
	return i, err
}

const createOAuthRefreshToken = `-- name: CreateOAuthRefreshToken :one
INSERT INTO oauth_refresh_tokens (token_hash, access_token_id, client_id, user_id, scope, expires_at)
VALUES (
  $1,
  $2::uuid,
  $3,
  $4::uuid,
  $5,
  $6
)
RETURNING id::text AS id,
          token_hash,
          access_token_id::text AS access_token_id,
          client_id,
          user_id::text AS user_id,
          scope,
          expires_at,
          revoked_at,
          created_at
`

type CreateOAuthRefreshTokenParams struct {
	TokenHash     string             `json:"token_hash"`
	AccessTokenID string             `json:"access_token_id"`
	ClientID      string             `json:"client_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Scope         string             `json:"scope"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type CreateOAuthRefreshTokenRow struct {
	ID            string             `json:"id"`
	TokenHash     string             `json:"token_hash"`
	AccessTokenID string             `json:"access_token_id"`
	ClientID      string             `json:"client_id"`
	UserID        string             `json:"user_id"`
	Scope         string             `json:"scope"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOAuthRefreshToken(ctx context.Context, arg CreateOAuthRefreshTokenParams) (CreateOAuthRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createOAuthRefreshToken,
		arg.TokenHash,
		arg.AccessTokenID,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i CreateOAuthRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AccessTokenID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, expires_at)
VALUES ($1::uuid, $2, $3)
RETURNING id::text AS id,
          user_id::text AS user_id,
          refresh_token_hash,
          expires_at,
          created_at
`

type CreateSessionParams struct {
	UserID           string             `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type CreateSessionRow struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (user_id, credential_id, public_key, sign_count, transports, metadata)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id::text AS id,
          user_id::text AS user_id,
          credential_id,
          public_key,
          sign_count,
          transports,
          metadata,
          created_at
`

type CreateWebAuthnCredentialParams struct {
	UserID       string   `json:"user_id"`
	CredentialID string   `json:"credential_id"`
	PublicKey    []byte   `json:"public_key"`
	SignCount    int64    `json:"sign_count"`
	Transports   []string `json:"transports"`
	Metadata     []byte   `json:"metadata"`
}

type CreateWebAuthnCredentialRow struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	CredentialID string             `json:"credential_id"`
	PublicKey    []byte             `json:"public_key"`
	SignCount    int64              `json:"sign_count"`
	Transports   []string           `json:"transports"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (CreateWebAuthnCredentialRow, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Metadata,
	)
	var i CreateWebAuthnCredentialRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionByID = `-- name: DeleteSessionByID :execrows
DELETE FROM sessions
WHERE id = $1::uuid
`

func (q *Queries) DeleteSessionByID(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByID, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthChallengeByID = `-- name: GetAuthChallengeByID :one
SELECT id::text AS id,
       challenge_type,
       user_id::text AS user_id,
       data,
       expires_at,
       consumed_at,
       created_at
FROM auth_challenges
WHERE id = $1::uuid
`

type GetAuthChallengeByIDRow struct {
	ID            string             `json:"id"`
	ChallengeType string             `json:"challenge_type"`
	UserID        string             `json:"user_id"`
	Data          []byte             `json:"data"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAuthChallengeByID(ctx context.Context, challengeID string) (GetAuthChallengeByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthChallengeByID, challengeID)
	var i GetAuthChallengeByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChallengeType,
		&i.UserID,
		&i.Data,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalIdentityByProviderSubject = `-- name: GetExternalIdentityByProviderSubject :one
SELECT id::text AS id,
       user_id::text AS user_id,
       provider,
       provider_subject,
       email,
       metadata,
       created_at
FROM external_identities
WHERE provider = $1
  AND provider_subject = $2
`

type GetExternalIdentityByProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

type GetExternalIdentityByProviderSubjectRow struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	Email           pgtype.Text        `json:"email"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetExternalIdentityByProviderSubject(ctx context.Context, arg GetExternalIdentityByProviderSubjectParams) (GetExternalIdentityByProviderSubjectRow, error) {
	row := q.db.QueryRow(ctx, getExternalIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i GetExternalIdentityByProviderSubjectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccessTokenByHash = `-- name: GetOAuthAccessTokenByHash :one
SELECT id::text AS id,
       token_hash,
       token_jti,
       client_id,
       user_id::text AS user_id,
       scope,
       expires_at,
       revoked_at,
       created_at
FROM oauth_access_tokens
WHERE token_hash = $1
`

type GetOAuthAccessTokenByHashRow struct {
	ID        string             `json:"id"`
	TokenHash string             `json:"token_hash"`
	TokenJti  string             `json:"token_jti"`
	ClientID  string             `json:"client_id"`
	UserID    string             `json:"user_id"`
	Scope     string             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOAuthAccessTokenByHash(ctx context.Context, tokenHash string) (GetOAuthAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccessTokenByHash, tokenHash)
	var i GetOAuthAccessTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenJti,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAuthorizationCodeByHash = `-- name: GetOAuthAuthorizationCodeByHash :one
SELECT id::text AS id,
       code_hash,
       client_id,
       user_id::text AS user_id,
       redirect_uri,
       scope,
       code_challenge,
       code_challenge_method,
       expires_at,
       consumed_at,
       created_at
FROM oauth_authorization_codes
WHERE code_hash = $1
`

type GetOAuthAuthorizationCodeByHashRow struct {
	ID                  string             `json:"id"`
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	UserID              string             `json:"user_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scope               string             `json:"scope"`
	CodeChallenge       pgtype.Text        `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text        `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOAuthAuthorizationCodeByHash(ctx context.Context, codeHash string) (GetOAuthAuthorizationCodeByHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationCodeByHash, codeHash)
	var i GetOAuthAuthorizationCodeByHashRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClientByID = `-- name: GetOAuthClientByID :one
SELECT id,
       name,
       redirect_uris,
       scopes,
       confidential,
       created_at,
       client_secret_hash,
       require_pkce
FROM oauth_clients
WHERE id = $1
`

func (q *Queries) GetOAuthClientByID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.Scopes,
		&i.Confidential,
		&i.CreatedAt,
		&i.ClientSecretHash,
		&i.RequirePkce,
	)
	return i, err
}

const getOAuthRefreshTokenByHash = `-- name: GetOAuthRefreshTokenByHash :one
SELECT id::text AS id,
       token_hash,
       access_token_id::text AS access_token_id,
       client_id,
       user_id::text AS user_id,
       scope,
       expires_at,
       revoked_at,
       created_at
FROM oauth_refresh_tokens
WHERE token_hash = $1
`

type GetOAuthRefreshTokenByHashRow struct {
	ID            string             `json:"id"`
	TokenHash     string             `json:"token_hash"`
	AccessTokenID string             `json:"access_token_id"`
	ClientID      string             `json:"client_id"`
	UserID        string             `json:"user_id"`
	Scope         string             `json:"scope"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOAuthRefreshTokenByHash(ctx context.Context, tokenHash string) (GetOAuthRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthRefreshTokenByHash, tokenHash)
	var i GetOAuthRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AccessTokenID,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id::text AS id,
       user_id::text AS user_id,
       refresh_token_hash,
       expires_at,
       created_at
FROM sessions
WHERE refresh_token_hash = $1
`

type GetSessionByRefreshTokenHashRow struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (GetSessionByRefreshTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i GetSessionByRefreshTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT id::text AS id,
       user_id::text AS user_id,
       credential_id,
       public_key,
       sign_count,
       transports,
       metadata,
       created_at
FROM webauthn_credentials
WHERE credential_id = $1
`

type GetWebAuthnCredentialByCredentialIDRow struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	CredentialID string             `json:"credential_id"`
	PublicKey    []byte             `json:"public_key"`
	SignCount    int64              `json:"sign_count"`
	Transports   []string           `json:"transports"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID string) (GetWebAuthnCredentialByCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByCredentialID, credentialID)
	var i GetWebAuthnCredentialByCredentialIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listWebAuthnCredentialsByUserID = `-- name: ListWebAuthnCredentialsByUserID :many
SELECT id::text AS id,
       user_id::text AS user_id,
       credential_id,
       public_key,
       sign_count,
       transports,
       metadata,
       created_at
FROM webauthn_credentials
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

type ListWebAuthnCredentialsByUserIDRow struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	CredentialID string             `json:"credential_id"`
	PublicKey    []byte             `json:"public_key"`
	SignCount    int64              `json:"sign_count"`
	Transports   []string           `json:"transports"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWebAuthnCredentialsByUserID(ctx context.Context, userID string) ([]ListWebAuthnCredentialsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebAuthnCredentialsByUserIDRow
	for rows.Next() {
		var i ListWebAuthnCredentialsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthAccessTokenByHash = `-- name: RevokeOAuthAccessTokenByHash :exec
UPDATE oauth_access_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthAccessTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeOAuthAccessTokenByHash, tokenHash)
	return err
}

const revokeOAuthRefreshTokenByHash = `-- name: RevokeOAuthRefreshTokenByHash :exec
UPDATE oauth_refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeOAuthRefreshTokenByHash, tokenHash)
	return err
}
