// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         int64              `json:"id"`
	ActorType  string             `json:"actor_type"`
	ActorID    string             `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	TargetID   pgtype.Text        `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OauthClient struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	RedirectUris []string           `json:"redirect_uris"`
	Scopes       []string           `json:"scopes"`
	Confidential bool               `json:"confidential"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PlatformPolicy struct {
	ID          int64              `json:"id"`
	AuthSurface string             `json:"auth_surface"`
	PlatformID  string             `json:"platform_id"`
	Mode        string             `json:"mode"`
	Entries     []string           `json:"entries"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type SubjectPolicyOverride struct {
	ID          int64              `json:"id"`
	AuthSurface string             `json:"auth_surface"`
	SubjectType string             `json:"subject_type"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	PlatformID  string             `json:"platform_id"`
	Decision    string             `json:"decision"`
	Reason      pgtype.Text        `json:"reason"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserAuthMethod struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MethodType      string             `json:"method_type"`
	ProviderSubject pgtype.Text        `json:"provider_subject"`
	SecretRef       pgtype.Text        `json:"secret_ref"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type UserGroup struct {
	UserID    pgtype.UUID        `json:"user_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
