// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformPolicy = `-- name: GetPlatformPolicy :one
SELECT id,
       auth_surface,
       platform_id,
       mode,
       entries,
       updated_at
FROM platform_policies
WHERE auth_surface = $1
  AND platform_id = $2
`

type GetPlatformPolicyParams struct {
	AuthSurface string `json:"auth_surface"`
	PlatformID  string `json:"platform_id"`
}

func (q *Queries) GetPlatformPolicy(ctx context.Context, arg GetPlatformPolicyParams) (PlatformPolicy, error) {
	row := q.db.QueryRow(ctx, getPlatformPolicy, arg.AuthSurface, arg.PlatformID)
	var i PlatformPolicy
	err := row.Scan(
		&i.ID,
		&i.AuthSurface,
		&i.PlatformID,
		&i.Mode,
		&i.Entries,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectPolicyOverride = `-- name: GetSubjectPolicyOverride :one
SELECT id,
       auth_surface,
       subject_type,
       subject_id::text AS subject_id,
       platform_id,
       decision,
       reason,
       updated_at
FROM subject_policy_overrides
WHERE auth_surface = $1
  AND subject_type = $2
  AND subject_id = $3::uuid
  AND platform_id = $4
`

type GetSubjectPolicyOverrideParams struct {
	AuthSurface string `json:"auth_surface"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
	PlatformID  string `json:"platform_id"`
}

type GetSubjectPolicyOverrideRow struct {
	ID          int64              `json:"id"`
	AuthSurface string             `json:"auth_surface"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	PlatformID  string             `json:"platform_id"`
	Decision    string             `json:"decision"`
	Reason      pgtype.Text        `json:"reason"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSubjectPolicyOverride(ctx context.Context, arg GetSubjectPolicyOverrideParams) (GetSubjectPolicyOverrideRow, error) {
	row := q.db.QueryRow(ctx, getSubjectPolicyOverride,
		arg.AuthSurface,
		arg.SubjectType,
		arg.SubjectID,
		arg.PlatformID,
	)
	var i GetSubjectPolicyOverrideRow
	err := row.Scan(
		&i.ID,
		&i.AuthSurface,
		&i.SubjectType,
		&i.SubjectID,
		&i.PlatformID,
		&i.Decision,
		&i.Reason,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatformPolicy = `-- name: UpsertPlatformPolicy :one
INSERT INTO platform_policies (
  auth_surface,
  platform_id,
  mode,
  entries,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  NOW()
)
ON CONFLICT (auth_surface, platform_id)
DO UPDATE SET
  mode = EXCLUDED.mode,
  entries = EXCLUDED.entries,
  updated_at = NOW()
RETURNING id, auth_surface, platform_id, mode, entries, updated_at
`

type UpsertPlatformPolicyParams struct {
	AuthSurface string   `json:"auth_surface"`
	PlatformID  string   `json:"platform_id"`
	Mode        string   `json:"mode"`
	Entries     []string `json:"entries"`
}

func (q *Queries) UpsertPlatformPolicy(ctx context.Context, arg UpsertPlatformPolicyParams) (PlatformPolicy, error) {
	row := q.db.QueryRow(ctx, upsertPlatformPolicy,
		arg.AuthSurface,
		arg.PlatformID,
		arg.Mode,
		arg.Entries,
	)
	var i PlatformPolicy
	err := row.Scan(
		&i.ID,
		&i.AuthSurface,
		&i.PlatformID,
		&i.Mode,
		&i.Entries,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubjectPolicyOverride = `-- name: UpsertSubjectPolicyOverride :one
INSERT INTO subject_policy_overrides (
  auth_surface,
  subject_type,
  subject_id,
  platform_id,
  decision,
  reason,
  updated_at
)
VALUES (
  $1,
  $2,
  $3::uuid,
  $4,
  $5,
  $6,
  NOW()
)
ON CONFLICT (auth_surface, subject_type, subject_id, platform_id)
DO UPDATE SET
  decision = EXCLUDED.decision,
  reason = EXCLUDED.reason,
  updated_at = NOW()
RETURNING id,
          auth_surface,
          subject_type,
          subject_id::text AS subject_id,
          platform_id,
          decision,
          reason,
          updated_at
`

type UpsertSubjectPolicyOverrideParams struct {
	AuthSurface string      `json:"auth_surface"`
	SubjectType string      `json:"subject_type"`
	SubjectID   string      `json:"subject_id"`
	PlatformID  string      `json:"platform_id"`
	Decision    string      `json:"decision"`
	Reason      pgtype.Text `json:"reason"`
}

type UpsertSubjectPolicyOverrideRow struct {
	ID          int64              `json:"id"`
	AuthSurface string             `json:"auth_surface"`
	SubjectType string             `json:"subject_type"`
	SubjectID   string             `json:"subject_id"`
	PlatformID  string             `json:"platform_id"`
	Decision    string             `json:"decision"`
	Reason      pgtype.Text        `json:"reason"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSubjectPolicyOverride(ctx context.Context, arg UpsertSubjectPolicyOverrideParams) (UpsertSubjectPolicyOverrideRow, error) {
	row := q.db.QueryRow(ctx, upsertSubjectPolicyOverride,
		arg.AuthSurface,
		arg.SubjectType,
		arg.SubjectID,
		arg.PlatformID,
		arg.Decision,
		arg.Reason,
	)
	var i UpsertSubjectPolicyOverrideRow
	err := row.Scan(
		&i.ID,
		&i.AuthSurface,
		&i.SubjectType,
		&i.SubjectID,
		&i.PlatformID,
		&i.Decision,
		&i.Reason,
		&i.UpdatedAt,
	)
	return i, err
}
