// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPlatformPolicy(ctx context.Context, arg GetPlatformPolicyParams) (PlatformPolicy, error)
	GetSubjectPolicyOverride(ctx context.Context, arg GetSubjectPolicyOverrideParams) (SubjectPolicyOverride, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListUserAuthMethods(ctx context.Context, userID pgtype.UUID) ([]UserAuthMethod, error)
	ListUserGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error)
	UpsertPlatformPolicy(ctx context.Context, arg UpsertPlatformPolicyParams) (PlatformPolicy, error)
	UpsertSubjectPolicyOverride(ctx context.Context, arg UpsertSubjectPolicyOverrideParams) (SubjectPolicyOverride, error)
}

var _ Querier = (*Queries)(nil)
